[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nicegui-react"
version = "0.2.1"
description = "Embed and interact with React components from NiceGUI, in Python."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [{ name = "Pablo Schaffner", email = "pablo@puntorigen.com" }]
keywords = ["nicegui", "react", "vite", "frontend", "components", "python"]
dependencies = [
    "nicegui>=2.3.0",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Framework :: FastAPI",
    "Topic :: Software Development :: User Interfaces",
]

[project.urls]
Homepage = "https://github.com/puntorigen/nicegui-react"
Repository = "https://github.com/puntorigen/nicegui-react"
Issues = "https://github.com/puntorigen/nicegui-react/issues"

[tool.setuptools.packages.find]
include = ["nicegui_react*"]

[tool.setuptools.package-data]
nicegui_react = ["react.js", "templates/*.template"]
