"""Embed and interact with React components from NiceGUI, in Python.

This module exposes the :class:`React` element. It builds a user's React project
with Vite into a self-contained ES module that exports a ``mount()`` function,
serves it as a static asset, and mounts it inside a native NiceGUI Vue component.

Props flow from Python to React over NiceGUI's regular element-update channel
(the same websocket path used by every other NiceGUI element), so React stays
reactive to Python value changes in every mode, not just dev mode. Events flow
back from React to Python through NiceGUI's native event system.
"""

from __future__ import annotations

import asyncio
import atexit
import hashlib
import json
import os
import shutil
import subprocess
import sys
import weakref
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from nicegui import app, background_tasks, core
from nicegui.context import context
from nicegui.element import Element

# Directories that never contain source worth hashing, copying or watching.
_IGNORED_DIRS = {
    'node_modules', '.git', '.cache', '.idea', '__pycache__',
    '.nicegui_react_dist', '.nicegui_react', 'react_cache', 'react_cache_dev', 'dist', 'build',
}
# Files generated by this package; excluded from the source fingerprint so that
# regenerating them does not invalidate the cache.
_GENERATED_FILES = {
    '_nicegui_react_main.jsx',
    '_nicegui_react_vite.config.mjs',
    'project_hash.txt',
    'build_hash.txt',
    'src_hash.txt',
    'build_token.txt',
    'package-lock.json',
}

_ENTRY_FILENAME = '_nicegui_react_main.jsx'
_CONFIG_FILENAME = '_nicegui_react_vite.config.mjs'
_DIST_DIRNAME = '.nicegui_react_dist'
_META_DIRNAME = '.nicegui_react'

# Bump to force a rebuild of all cached bundles when the build logic changes.
_BUILDER_VERSION = '0.2.0'

_TEMPLATES_DIR = Path(__file__).parent / 'templates'


def _load_template(name: str) -> str:
    return (_TEMPLATES_DIR / name).read_text(encoding='utf-8')


def _write_if_changed(path: Path, content: str) -> bool:
    """Write ``content`` to ``path`` only if it differs. Returns True if written."""
    if path.exists() and path.read_text(encoding='utf-8') == content:
        return False
    path.write_text(content, encoding='utf-8')
    return True


class React(Element, component='react.js'):
    """A NiceGUI element that renders a React component.

    :param react_project_path: path to your React project directory (resolved relative to the calling script)
    :param main_component: name of the main React component to render
    :param component_id: unique identifier for the component instance (default: project folder name)
    :param env: environment variables exposed to the React app at build time as ``process.env.*``
    :param use_legacy_peer_deps: whether to pass ``--legacy-peer-deps`` to ``npm install``
    :param dev: enable development mode with live reload on source changes
    """

    # In-process registry of built bundles, keyed by component hash. Avoids
    # rebuilding or re-registering static routes on every instantiation.
    _bundles: Dict[str, Dict[str, Any]] = {}
    # Set of static URL paths already registered in this process.
    _static_mounts: set = set()
    # Dev watchers, keyed by component hash.
    _dev_watchers: Dict[str, 'React._DevWatcher'] = {}
    # Dev-mode build roots (resolved project dir -> component hash). Dev builds
    # happen in place, sharing one entry/config/output per directory, so a
    # project directory supports only one configuration at a time.
    _dev_build_roots: Dict[Path, str] = {}

    def __init__(
        self,
        react_project_path: str,
        main_component: Optional[str] = None,
        component_id: Optional[str] = None,
        env: Optional[dict] = None,
        use_legacy_peer_deps: bool = False,
        dev: bool = False,
    ) -> None:
        self._configure(
            self._caller_dir(),
            react_project_path, main_component, component_id, env, use_legacy_peer_deps, dev,
        )

        super().__init__()

        # Initialize props with sane defaults so the client component always
        # receives well-typed values.
        self.react_props: Dict[str, Any] = {}
        self.event_handlers: Dict[str, Callable] = {}
        self.events_to_listen: set = set()
        self._props['react_props'] = {}
        self._props['react_events'] = []
        self._props['bundle_url'] = ''
        self._props['css_urls'] = []
        self._props['reload_token'] = None

        info = self._ensure_built()
        self._props['bundle_url'] = info['bundle_url']
        self._props['css_urls'] = info['css_urls']
        self._props['reload_token'] = info['token']

        if self.dev:
            self._register_for_dev_reload()

    @classmethod
    def prebuild(
        cls,
        react_project_path: str,
        main_component: Optional[str] = None,
        component_id: Optional[str] = None,
        env: Optional[dict] = None,
        use_legacy_peer_deps: bool = False,
        dev: bool = False,
    ) -> Dict[str, Any]:
        """Build (and cache) a React project ahead of time, without a client.

        Call this from ``app.on_startup`` so the first page visit does not pay
        the one-time build cost. Arguments match :class:`React`. Safe to call
        repeatedly: it reuses the on-disk and in-process caches.
        """
        self = cls.__new__(cls)
        self._configure(
            cls._caller_dir(),
            react_project_path, main_component, component_id, env, use_legacy_peer_deps, dev,
        )
        return self._ensure_built()

    @staticmethod
    def _caller_dir() -> Path:
        """Directory of the user code that called __init__ or prebuild."""
        # frame 0: this method, frame 1: __init__/prebuild, frame 2: user code
        caller_globals = sys._getframe(2).f_globals
        if '__file__' in caller_globals:
            return Path(caller_globals['__file__']).resolve().parent
        return Path.cwd()

    def _configure(
        self,
        caller_dir: Path,
        react_project_path: str,
        main_component: Optional[str],
        component_id: Optional[str],
        env: Optional[dict],
        use_legacy_peer_deps: bool,
        dev: bool,
    ) -> None:
        # Resolve the project path relative to the caller's file (not the CWD),
        # preserving the historical behavior.
        self.original_project_path = (caller_dir / react_project_path).resolve()
        if not self.original_project_path.exists():
            raise FileNotFoundError(f'React project path does not exist: {self.original_project_path}')

        if component_id is None:
            component_id = self.original_project_path.stem
        self.component_id = component_id
        self.main_component = main_component
        self.use_legacy_peer_deps = use_legacy_peer_deps
        self.dev = dev
        self.env = env or {}

        self.component_hash = self._generate_unique_hash(component_id)

        if self.dev:
            # Build in place so that edits to the original project trigger live
            # reloads. Generated files use distinct names to avoid clobbering
            # any existing vite.config.js / main.jsx in the user's project.
            self.build_root = self.original_project_path
            # In-place builds share one entry/config/output per directory, so a
            # second configuration would silently overwrite the first's bundle.
            # Fail loudly instead (interim guard until dev builds are per-config).
            # The same configuration (same hash) stays allowed -- that is the
            # existing shared-watcher multi-instance path.
            registered = React._dev_build_roots.get(self.build_root)
            if registered is not None and registered != self.component_hash:
                raise RuntimeError(
                    'nicegui-react: dev=True builds in place, so each project directory supports '
                    'only one configuration (main_component/env/flags) at a time. A different '
                    f'configuration is already active for {self.build_root}. Use dev=False for '
                    'additional variants, or duplicate the project directory.'
                )
            React._dev_build_roots[self.build_root] = self.component_hash
        else:
            self.build_root = Path.home() / '.nicegui' / 'react_cache' / self.component_hash

        self.output_dir = self.build_root / _DIST_DIRNAME
        # Build metadata lives outside the Vite output dir, which is wiped on
        # every build (emptyOutDir), so stamps must survive rebuilds.
        self.meta_dir = self.build_root / _META_DIRNAME
        self.entry_path = self.build_root / _ENTRY_FILENAME
        self.config_path = self.build_root / _CONFIG_FILENAME
        self.package_json_path = self.build_root / 'package.json'
        self.static_path = f'/react/{self.component_hash}'

    # ------------------------------------------------------------------ API

    def props(self, **kwargs: Any) -> 'React':
        """Set or update props passed to the React component.

        Any change is pushed to the browser over NiceGUI's element-update
        channel and re-renders the React component, keeping it reactive to
        Python state in all modes.
        """
        old = dict(self.react_props)
        self.react_props.update(kwargs)
        if old != self.react_props:
            self._props['react_props'] = dict(self.react_props)
            self.update()
        return self

    def on(self, event_name: str, handler: Callable) -> 'React':  # type: ignore[override]
        """Register a handler for an event emitted from the React component.

        The handler is called with the event payload directly (as in previous
        versions). Both sync and async handlers are supported.
        """
        self.event_handlers[event_name] = handler
        if event_name not in self.events_to_listen:
            self.events_to_listen.add(event_name)
            self._props['react_events'] = sorted(self.events_to_listen)
            # Register a single native listener per event that dispatches to the
            # currently-registered handler, unwrapping the event arguments.
            super().on(event_name, lambda e, _name=event_name: self._dispatch_event(_name, e))
        self.update()
        return self

    # -------------------------------------------------------------- events

    def _dispatch_event(self, name: str, event: Any) -> Any:
        handler = self.event_handlers.get(name)
        if handler is None:
            return None
        # Returning a coroutine here lets NiceGUI's event machinery await it,
        # so async handlers work without special-casing.
        return handler(event.args)

    # --------------------------------------------------------------- build

    def _generate_unique_hash(self, component_id: str) -> str:
        # The key must include everything that changes the build output
        # (mirroring :meth:`_compute_source_fingerprint`). Otherwise two
        # instances sharing a project directory but differing in e.g.
        # ``main_component`` would collide on one cache key, and the
        # in-process bundle registry would silently serve the first
        # instance's bundle for the second.
        unique = '|'.join([
            component_id,
            str(self.original_project_path),
            str(self.main_component),
            json.dumps(self.env, sort_keys=True, default=str),
            'dev' if self.dev else 'prod',
            'legacy-peer-deps' if self.use_legacy_peer_deps else '',
        ])
        return 'react_' + hashlib.md5(unique.encode()).hexdigest()

    def _ensure_built(self) -> Dict[str, Any]:
        """Build the bundle if needed and return its serving info (cached)."""
        key = self.component_hash
        if key in React._bundles:
            return React._bundles[key]

        src_fingerprint = self._compute_source_fingerprint()
        bundle_file = self.output_dir / 'bundle.js'
        src_stamp = self.meta_dir / 'src_hash.txt'
        token_stamp = self.meta_dir / 'build_token.txt'
        cached = (
            bundle_file.exists()
            and src_stamp.exists()
            and src_stamp.read_text(encoding='utf-8').strip() == src_fingerprint
            and token_stamp.exists()
        )

        if not cached:
            self._prepare_project()
            self._install_dependencies()
            self._run_build()
            self.meta_dir.mkdir(parents=True, exist_ok=True)
            src_stamp.write_text(src_fingerprint, encoding='utf-8')
            token = self._compute_output_token()
            token_stamp.write_text(token, encoding='utf-8')
        else:
            token = token_stamp.read_text(encoding='utf-8').strip()
            if self.dev:
                # Even when the last build is current, make sure config/entry
                # exist for the watcher to pick up.
                self._prepare_project()

        info = self._collect_bundle_info(token)
        self._serve_bundle()
        React._bundles[key] = info
        return info

    def _compute_output_token(self) -> str:
        """Hash the built bundle so the served URL changes only when its content
        does. This guarantees browsers never serve a stale bundle."""
        return self._hash_output_files(self.output_dir)

    @staticmethod
    def _hash_output_files(output_dir: Path) -> str:
        hasher = hashlib.md5()
        for name in ('bundle.js', 'bundle.css'):
            path = output_dir / name
            if path.exists():
                hasher.update(path.read_bytes())
        return hasher.hexdigest()[:12]

    def _collect_bundle_info(self, token: str) -> Dict[str, Any]:
        css_files = sorted(p.name for p in self.output_dir.glob('*.css'))
        return {
            'bundle_url': f'{self.static_path}/bundle.js',
            'css_urls': [f'{self.static_path}/{name}?v={token}' for name in css_files],
            'token': token,
            'output_dir': str(self.output_dir),
        }

    def _compute_source_fingerprint(self) -> str:
        """Fast fingerprint from file paths, sizes and mtimes (no content reads).

        Also mixes in everything else that affects the build output (builder
        version, templates, dev flag, env, target component) so that changing
        any of them correctly invalidates the on-disk cache.
        """
        hasher = hashlib.md5()
        hasher.update(_BUILDER_VERSION.encode())
        hasher.update(b'dev' if self.dev else b'prod')
        hasher.update(json.dumps(self.env, sort_keys=True, default=str).encode())
        hasher.update(str(self.main_component).encode())
        for template in sorted(_TEMPLATES_DIR.glob('*.template')):
            hasher.update(template.read_bytes())
        root = self.original_project_path
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = sorted(d for d in dirnames if d not in _IGNORED_DIRS)
            for filename in sorted(filenames):
                if filename in _GENERATED_FILES or filename == '.DS_Store':
                    continue
                file_path = Path(dirpath) / filename
                try:
                    stat = file_path.stat()
                except OSError:
                    continue
                rel = file_path.relative_to(root).as_posix()
                hasher.update(f'{rel}|{stat.st_size}|{int(stat.st_mtime)}'.encode())
        return hasher.hexdigest()[:12]

    def _prepare_project(self) -> None:
        if not self.dev:
            self._copy_project_files()
        self._ensure_package_json()
        self._write_generated_files()

    def _copy_project_files(self) -> None:
        """Copy the user's project into the cache directory (non-dev mode)."""
        self.build_root.mkdir(parents=True, exist_ok=True)
        for item in self.original_project_path.iterdir():
            if item.name in _IGNORED_DIRS or item.name in _GENERATED_FILES:
                continue
            if item.resolve() == self.build_root.resolve():
                continue
            destination = self.build_root / item.name
            if item.is_dir():
                shutil.copytree(
                    item, destination,
                    ignore=shutil.ignore_patterns(*_IGNORED_DIRS),
                    dirs_exist_ok=True,
                )
            else:
                shutil.copy2(item, destination)

    def _ensure_package_json(self) -> bool:
        """Ensure package.json exists with the dependencies needed to build.

        Returns True if package.json was modified.
        """
        default_dev_deps = {
            'vite': '^5.4.10',
            '@vitejs/plugin-react': '^4.3.3',
        }
        default_deps = {
            'react': '^18.0.0',
            'react-dom': '^18.0.0',
        }
        default_scripts = {'dev': 'vite', 'build': 'vite build'}

        if not self.package_json_path.exists():
            package = {
                'name': 'nicegui-react-app',
                'version': '1.0.0',
                'private': True,
                'scripts': default_scripts,
                'dependencies': default_deps,
                'devDependencies': default_dev_deps,
            }
            self.package_json_path.write_text(json.dumps(package, indent=2), encoding='utf-8')
            return True

        package = json.loads(self.package_json_path.read_text(encoding='utf-8'))
        original = json.dumps(package, sort_keys=True)

        dependencies = package.setdefault('dependencies', {})
        dev_dependencies = package.setdefault('devDependencies', {})
        scripts = package.setdefault('scripts', {})

        # Respect any versions the user already declared; only fill gaps.
        for dep, version in default_deps.items():
            dependencies.setdefault(dep, version)
        for dep, version in default_dev_deps.items():
            dev_dependencies.setdefault(dep, version)
        for name, command in default_scripts.items():
            scripts.setdefault(name, command)

        if json.dumps(package, sort_keys=True) != original:
            self.package_json_path.write_text(json.dumps(package, indent=2), encoding='utf-8')
            return True
        return False

    def _get_dependency_versions(self) -> Dict[str, Dict[str, str]]:
        package = json.loads(self.package_json_path.read_text(encoding='utf-8'))
        return {
            'dependencies': package.get('dependencies', {}),
            'devDependencies': package.get('devDependencies', {}),
        }

    def _write_generated_files(self) -> None:
        self._write_vite_config()
        self._write_entry()

    def _write_vite_config(self) -> None:
        deps = self._get_dependency_versions()
        vite_version = deps['devDependencies'].get('vite', '^5.0.0')
        try:
            vite_major = int(vite_version.lstrip('^~>=< ').split('.')[0])
        except (ValueError, IndexError):
            vite_major = 5
        react_plugin_call = 'react()' if vite_major >= 5 else "react({ jsxRuntime: 'classic' })"

        output_relative = os.path.relpath(self.output_dir, start=self.build_root).replace('\\', '/')

        # NODE_ENV must be defined so React (and other libraries) do not hit an
        # undefined `process` at runtime in the browser. It also enables dead-code
        # elimination of React's development-only branches in production builds.
        #
        # Vite/esbuild `define` performs a raw text substitution, so each value
        # must itself be a string containing valid JS. We therefore JSON-encode
        # twice: once to turn the Python value into a JS literal, and again to
        # embed that literal as a JS string in the config.
        define_entries = {
            'process.env.NODE_ENV': 'development' if self.dev else 'production',
        }
        for key, value in self.env.items():
            define_entries[f'process.env.{key}'] = value
        entries = ',\n    '.join(
            f"'{key}': {json.dumps(json.dumps(value))}"
            for key, value in define_entries.items()
        )
        define_section = f'define: {{\n    {entries}\n  }},'

        content = (
            _load_template('vite.config.js.template')
            .replace('__REACT_PLUGIN_IMPORT__', '@vitejs/plugin-react')
            .replace('__REACT_PLUGIN_CALL__', react_plugin_call)
            .replace('__DEFINE_SECTION__', define_section)
            .replace('__OUT_DIR__', output_relative)
            .replace('__ENTRY__', _ENTRY_FILENAME)
            .replace('__MINIFY__', 'false' if self.dev else 'true')
        )
        _write_if_changed(self.config_path, content)

    def _write_entry(self) -> None:
        if not self.main_component:
            raise ValueError('main_component must be specified when initializing the React class.')

        component_file = self._find_component_file(self.main_component)
        if component_file is None:
            raise FileNotFoundError(
                f"Component '{self.main_component}' not found in '{self.build_root}'.")

        import_path = component_file.relative_to(self.build_root).as_posix()
        if not import_path.startswith('.'):
            import_path = './' + import_path

        is_default = 'export default' in component_file.read_text(encoding='utf-8')
        if is_default:
            component_import = f"import {self.main_component} from '{import_path}';"
        else:
            component_import = f"import {{ {self.main_component} }} from '{import_path}';"

        react_version = self._get_dependency_versions()['dependencies'].get('react', '^18.0.0')
        try:
            react_major = int(react_version.lstrip('^~>=< ').split('.')[0])
        except (ValueError, IndexError):
            react_major = 18

        if react_major >= 18:
            reactdom_import = 'import { createRoot } from "react-dom/client";'
            root_setup = 'const root = createRoot(container);'
            render_call = 'root.render(element);'
            unmount_call = 'root.unmount();'
        else:
            reactdom_import = 'import ReactDOM from "react-dom";'
            root_setup = ''
            render_call = 'ReactDOM.render(element, container);'
            unmount_call = 'ReactDOM.unmountComponentAtNode(container);'

        content = (
            _load_template('main.jsx.template')
            .replace('__REACTDOM_IMPORT__', reactdom_import)
            .replace('__COMPONENT_IMPORT__', component_import)
            .replace('__COMPONENT_NAME__', self.main_component)
            .replace('__ROOT_SETUP__', root_setup)
            .replace('__RENDER__', render_call)
            .replace('__UNMOUNT__', unmount_call)
        )
        _write_if_changed(self.entry_path, content)

    def _find_component_file(self, name: str) -> Optional[Path]:
        for ext in ('*.jsx', '*.tsx', '*.js', '*.ts'):
            for candidate in self.build_root.rglob(ext):
                # Only consider path parts relative to the build root, since the
                # build root itself may live under an ignored directory name
                # (e.g. ~/.nicegui/react_cache/...).
                rel_parts = candidate.relative_to(self.build_root).parts
                if any(part in _IGNORED_DIRS for part in rel_parts):
                    continue
                if candidate.stem == name:
                    return candidate
        return None

    def _install_dependencies(self) -> None:
        node_modules = self.build_root / 'node_modules'
        package_lock = self.build_root / 'package-lock.json'
        needs_install = (
            not node_modules.exists()
            or not package_lock.exists()
            or self.package_json_path.stat().st_mtime > package_lock.stat().st_mtime
        )
        if not needs_install:
            return
        command = ['npm', 'install']
        if self.use_legacy_peer_deps:
            command.append('--legacy-peer-deps')
        subprocess.run(command, cwd=self.build_root, check=True)

    def _vite_command(self, *extra: str) -> List[str]:
        local_vite = self.build_root / 'node_modules' / '.bin' / 'vite'
        base = [str(local_vite)] if local_vite.exists() else ['npx', 'vite']
        return base + ['build', '--config', _CONFIG_FILENAME, *extra]

    def _run_build(self) -> None:
        try:
            result = subprocess.run(
                self._vite_command(),
                cwd=self.build_root,
                check=True,
                capture_output=True,
                text=True,
            )
            if result.stdout:
                print(result.stdout)
        except subprocess.CalledProcessError as error:
            print('nicegui-react: Vite build failed')
            print(error.stdout)
            print(error.stderr)
            raise

    def _serve_bundle(self) -> None:
        if self.static_path in React._static_mounts:
            return
        self.output_dir.mkdir(parents=True, exist_ok=True)
        app.add_static_files(self.static_path, str(self.output_dir))
        React._static_mounts.add(self.static_path)

    # ----------------------------------------------------------- dev mode

    def _register_for_dev_reload(self) -> None:
        watcher = React._dev_watchers.get(self.component_hash)
        if watcher is None:
            watcher = React._DevWatcher(self)
            React._dev_watchers[self.component_hash] = watcher
            watcher.start()
        watcher.add_element(self)

    class _DevWatcher:
        """Runs ``vite build --watch`` and pushes reloads to live elements."""

        POLL_INTERVAL = 0.4

        def __init__(self, prototype: 'React') -> None:
            self.build_root = prototype.build_root
            self.output_dir = prototype.output_dir
            self.static_path = prototype.static_path
            self.component_hash = prototype.component_hash
            self._vite_command = prototype._vite_command('--watch')
            self._elements: 'List[weakref.ref]' = []
            self._process: Optional[subprocess.Popen] = None
            self._task: Optional[asyncio.Task] = None

        def add_element(self, element: 'React') -> None:
            self._elements.append(weakref.ref(element))

        def _terminate(self) -> None:
            if self._process is not None and self._process.poll() is None:
                self._process.terminate()

        def start(self) -> None:
            if self._process is None:
                self._process = subprocess.Popen(
                    self._vite_command,
                    cwd=self.build_root,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                atexit.register(self._terminate)
            if self._task is None and core.loop is not None:
                self._task = background_tasks.create(self._poll(), name=f'nicegui-react-watch-{self.component_hash}')

        async def _poll(self) -> None:
            bundle = self.output_dir / 'bundle.js'
            last_mtime = bundle.stat().st_mtime if bundle.exists() else 0.0
            while True:
                await asyncio.sleep(self.POLL_INTERVAL)
                if not bundle.exists():
                    continue
                mtime = bundle.stat().st_mtime
                if mtime == last_mtime:
                    continue
                last_mtime = mtime
                self._push_reload()

        def _push_reload(self) -> None:
            token = React._hash_output_files(self.output_dir)
            info = React._bundles.get(self.component_hash)
            if info is not None:
                info['token'] = token
                info['css_urls'] = [
                    url.split('?')[0] + f'?v={token}' for url in info['css_urls']
                ]
            alive: 'List[weakref.ref]' = []
            for ref in self._elements:
                element = ref()
                if element is None:
                    continue
                alive.append(ref)
                try:
                    if element.is_deleted:
                        continue
                    element._props['reload_token'] = token
                    if info is not None:
                        element._props['css_urls'] = info['css_urls']
                    element.update()
                except Exception:  # noqa: BLE001 - client may have disconnected
                    pass
            self._elements = alive
